name: template_bloc
description: A Flutter project template with Clean Architecture, Bloc state management, and comprehensive features.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.6
  # flutter_screenutil: ^5.9.0
  # responsive_framework: ^1.1.0
  flutter_localizations:
    sdk: flutter
  
  # State Management
  # flutter_bloc: ^8.1.3
  # bloc_concurrency: ^0.2.2
  
  # Utils
  # equatable: ^2.0.5
  # dartz: ^0.10.1
  # logger: ^2.0.2+1
  intl: ^0.20.2
  # url_launcher: ^6.2.1
  # package_info_plus: ^4.2.0
  # device_info_plus: ^9.1.1
  
  # Security
  # flutter_secure_storage: ^9.0.0
  # crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  # build_runner: ^2.4.7
  # json_serializable: ^6.7.1
  
  # Testing
  # bloc_test: ^9.1.4
  # mockito: ^5.4.4
  integration_test:
    sdk: flutter
  
  # Linting & Analysis
  flutter_lints: ^3.0.1
  # custom_lint: ^0.5.7
  
  # Coverage
  # coverage: ^1.6.3

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/translations/
  
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Roboto-Light.ttf
  #         weight: 300
